name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[vars]
G_CLIENT_ID = "Ov23li6vtxpYhkhxvHhA"
G_CLIENT_SECRET = "1384a35408332adac8cce88d57cdb3d292213286"
JWT_SECRET = "o.O?327878"
INIT_TABLE = "true"
ENABLE_CACHE = "true"
NEWSNOW_DB = "newsnow-db"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "a9654a46-1c76-4ebe-be39-43f3dedee258"
